export const PicItems = [
    {
        picName:"finn",
        picURL:"/prismo-pics/finn.jpg",
    },
    {
        picName:"jake",
        picURL:"/prismo-pics/jake.jpg",
    },
    {
        picName:"bmo",
        picURL:"/prismo-pics/bmo.jpg",
    },
    {
        picName:"lsp",
        picURL:"/prismo-pics/lsp.jpg",
    },
    {
        picName:"marci",
        picURL:"/prismo-pics/marci.jpg",
    },
    {
        picName:"pb",
        picURL:"/prismo-pics/pb.jpg",
    },
]